<a href="https://colab.research.google.com/github/ychaulagain/pytorch-end-to-end/blob/main/notebooks/01_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01 - PyTorch Tensors

## Goals
By the end of this notebook, you will be able to:
- Create tensors in multiple ways
- Inspect shape, dtype, and device
- Reshape and index tensors
- Perform basic math operations
- Understand broadcasting (with examples)
- Move tensors between CPU and GPU (if available)

In [ ]:
import torch
print("PyTorch version", torch.__version__)
print("CUDA available", torch.cuda.is_available())

PyTorch version 2.9.0+cpu
CUDA available False


## 1. Creating tensors

Tensors are the core data structure in PyTorch.
Yor can create them from:
- Python lists
- NumPy arrays
- Factory methods like 'zeros', 'ones', 'rand', 'arrange'

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
a, b

(tensor([1, 2, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [ ]:
print("a:", a)
print("shape:", a.shape)
print("dtype:", a.dtype)
print("device:", a.device)

a: tensor([1, 2, 3])
shape: torch.Size([3])
dtype: torch.int64
device: cpu


## 2. Tensor dtypes
`dtype` controls the type of numbers in a tensor (int, float, etc).
This matters for:
- memory usuage
- model training (most training uses float32)

In [ ]:
x_int = torch.tensor([1, 2, 3], dtype=torch.int)
x_float = torch.tensor([1, 2, 3], dtype=torch.float)
print(x_int, x_int.dtype)
print(x_float, x_float.dtype)

tensor([1, 2, 3], dtype=torch.int32) torch.int32
tensor([1., 2., 3.]) torch.float32


In [ ]:
x = torch.tensor([1, 2, 3])
x = x.to(torch.float32)
print(x, x.dtype)

tensor([1., 2., 3.]) torch.float32


## 3. Factory methods

In [ ]:
z = torch.zeros((2, 3))
o = torch.ones((2, 3))
r = torch.rand((2, 3))         # random in [0, 1]
seq = torch.arange(0, 10, 2)   # 0,2,4,6,8
z, o, r, seq

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0.6728, 0.1508, 0.2659],
         [0.3438, 0.6883, 0.4875]]),
 tensor([0, 2, 4, 6, 8]))

In [ ]:
like_z = torch.zeros_like(r)
like_r = torch.rand_like(o)
like_z, like_r

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0.6763, 0.3244, 0.2528],
         [0.8387, 0.1682, 0.6049]]))

## 4. Shape and reshaping

Shpaes are critical in deep learning.

Common reshape operations:
- `reshape`
- `view` (similar but needs contiguous memory)
- `squeeze` / `unsqueeze`

In [ ]:
t = torch.arange(0, 12) # 12 elements
t2 = t.reshape(3, 4)
print("t shape:", t.shape)
print("t2 shape:", t2.shape)
t2

t shape: torch.Size([12])
t2 shape: torch.Size([3, 4])


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
v = torch.tensor([10, 20, 30]) # shape (3, )

v_unsq0 = v.unsqueeze(0) # add dimension at front -> (1, 3)
v_unsq1 = v.unsqueeze(1) # add dimension at end -> (3, 1)

print("v:", v.shape)
print("unsqueeze(0):", v_unsq0.shape)
print("unsqueeze(1):", v_unsq1.shape)

print("squeeze back:", v_unsq0.squeeze(0).shape)

v: torch.Size([3])
unsqueeze(0): torch.Size([1, 3])
unsqueeze(1): torch.Size([3, 1])
squeeze back: torch.Size([3])


## 5. Indexing and slicing

Indexing tesnsors is similar to NumPy.

In [ ]:
m = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])
m.shape

torch.Size([2, 3])

## 6. Basic tensor operations

PyTorch supports:
- elementswise ops: +, -, *, /
- matrix multipication: `@` or `torch.matmul`
- reductions: sum, mean, max

In [13]:
p = torch.tensor([1.0, 2.0, 3.0])
q = torch.tensor([10.0, 20.0, 30.0])

print("p + q:", p + q)
print("p - q:", p - q)
print("p * q:", p * q)
print("p / q:", p / q)

p + q: tensor([11., 22., 33.])
p - q: tensor([ -9., -18., -27.])
p * q: tensor([10., 40., 90.])
p / q: tensor([0.1000, 0.1000, 0.1000])


In [14]:
A = torch.rand((2, 3))
B = torch.rand((3, 4))

C = A @ B
print("A shape:", A.shape)
print("B shape:", B.shape)
print("C shape:", C.shape)

A shape: torch.Size([2, 3])
B shape: torch.Size([3, 4])
C shape: torch.Size([2, 4])


In [17]:
x = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0]])
print("x sum:", x.sum())
print("x mean:", x.mean())
print("x max:", x.max())
print("argmax", x.argmax())

x sum: tensor(10.)
x mean: tensor(2.5000)
x max: tensor(4.)
argmax tensor(3)


## 7. Broadcasting
Broadcasting lets PyTorch combine tensors of different shapes by automatically expanding dimensions when possible.

This is extremely common in deep learning.

In [20]:
M = torch.ones((3,4))
v = torch.tensor([1.0, 2.0, 3.0, 4.0]) # shape (4, )

out = M + v # v broadcasts across rows
print(M)
print(v)
print("M shape:", M.shape)
print("v shape:", v.shape)
print("out shape:", out.shape)
out

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 2., 3., 4.])
M shape: torch.Size([3, 4])
v shape: torch.Size([4])
out shape: torch.Size([3, 4])


tensor([[2., 3., 4., 5.],
        [2., 3., 4., 5.],
        [2., 3., 4., 5.]])

In [21]:
# Example: adding a column vector
col = torch.tensor([10.0, 20.0, 30.0]).unsqueeze(1) # shape (3, 1)
print(col)
out2 = M + col
print("col shape", col.shape)
print("out2 shape", out2.shape)
out2

tensor([[10.],
        [20.],
        [30.]])
col shape torch.Size([3, 1])
out2 shape torch.Size([3, 4])


tensor([[11., 11., 11., 11.],
        [21., 21., 21., 21.],
        [31., 31., 31., 31.]])

## 8. CPU vs GPU (device)

If CUDA is available, you can move tensors to GPU for faster compute.

In [22]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using devide:", device)

x = torch.rand((2, 2))
x = x.to(device)
print("x device:", x.device)

Using devide: cpu
x device: cpu


## Common mistakes
- Forgetting to check shapes (`tensor.shape`)
- Mixing dtypes (int vs float) when computing
- Mixing devices (CPU tensor + GPU tensor) causes errors
- Using `@` when you meant elementwise `*` (and vice versa)


## Summary
You learned how to:
- Create tensors in different ways
- Inspect and change `shape`, `dtype`, and `device`
- Index and slice tensors
- Use elementwise ops, matrix multiplication, and reductions
- Understand broadcasting

